### ISSUE TITLE
software loads, diagrams not forming

### ISSUE THREAD

**Issue by alibama** [jtlicardo/bpmn-assistant#1]
Excited to test this further - i've added both api keys in the .env and the software is loading fine, however when i click new chat it doesn't clears the text area and doesn't render

<img width="1238" alt="Screenshot 2024-07-18 at 9 54 03 AM" src="https://github.com/user-attachments/assets/69b91476-fe42-46d6-9286-dee44c20ff9a">

also - do you think 1000 characters could be edited?  i'm trying to paste https://www.charlottesville.gov/216/Starting-a-Small-Business in and it's about 10,000 characters?

**Comment by jtlicardo** [comment]
I added a 'Send' button, but you can also send a message by pressing Enter. The 'New chat' button is indeed for starting a new chat - should be disabled when there are no messages in the current chat.

The character limit may be increased in the future, need to test it with longer inputs. Until then I suggest you try to summarize the process - maybe even by using another LLM.

![image](https://github.com/user-attachments/assets/fda99a4c-5390-4810-a440-b216f945aeba)
