### ISSUE TITLE
thoughts on ollama or other open source llm integration

### ISSUE THREAD

**Issue by alibama** [jtlicardo/bpmn-assistant#11]
hey - we're starting to use BPMN Assistant to generate models for - https://lexipedia.xyz/ = I'd like to add an ollama llm integration point = could you help advise on how best to approach that?  we have 4 data science masters students and i want to get them testing new process extraction ideas and see how they fit in = 

thank you for considering!

**Comment by jtlicardo** [comment]
Hey, that's very cool! I think the Ollama integration idea is a good one and something I’d definitely do if I had the time, but right now I’m tied up with other things. Maybe I’ll have some time to look into it soon. Feel free to tag me if you run into specific questions, and I’ll try to assist when I can.

Thanks!

**Comment by alibama** [comment]
right on - looks like the main thing is getting ollama's functionality in the provider_impl directory and then updating the configs 

i'm basing the new product on openai since there should be reasonable compatability there?  the ollama library in python includes some chat functions too...

**Comment by jtlicardo** [comment]
Added Llama 3.3 70B, Qwen 2.5 72B and QwQ 32B, provided by [Fireworks AI](https://fireworks.ai/). Running these models locally would probably not be feasible for most users, so I’m not planning to add Ollama at this time. Open to exploring it further if the need arises.
