### ISSUE TITLE
OPENAI API Key Issue

### ISSUE THREAD

**Issue by tilmanotto** [jtlicardo/bpmn-assistant#12]
Unfortunately a Project API key or User API key from OpenAI raises the error: 
` You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
bpmn_assistant-1      | INFO:     172.20.0.1:36618 - "POST /determine_intent HTTP/1.1" 500 Internal Server Error`

But it works with python sample app provided by OpenAI.

**Comment by alibama** [comment]
are you sure it's formatted properly in your .env file?

OPENAI_API_KEY='key-goes-here'

make sure you have the single quotes in place?

**Comment by jtlicardo** [comment]
@tilmanotto Is this issue resolved?
