### ISSUE TITLE
Max number of retries reached. model times out

### ISSUE THREAD

**Issue by alibama** [jtlicardo/bpmn-assistant#3]
things are getting better - i put in the following text to test with 

build this "Contact the City of Charlottesville Zoning Office at 434-970-3182 for site approval, including building structural changes. Download a Business License Zoning Approval Application(pdf) If conducting business from your home, you will need a Home Occupation Provisional Use Permit (PDF) If erecting a sign at your business location, you will need a Sign Permit (PDF)"

and the response came through

It looks like you want to create a BPMN process for obtaining site approval and necessary permits from the City of Charlottesville Zoning Office. Would you like me to help you design this process? If so, I can create a new BPMN diagram for you."

and i said "yes" and things got started, however the model timed out?

<img width="1512" alt="Screenshot 2024-07-18 at 10 38 34 AM" src="https://github.com/user-attachments/assets/019bb09d-64b5-451d-9428-13cba032f8d9">

bpmn_frontend-1       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
bpmn_frontend-1       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
bpmn_frontend-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
bpmn_frontend-1       | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
bpmn_frontend-1       | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
bpmn_frontend-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
bpmn_frontend-1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
bpmn_frontend-1       | /docker-entrypoint.sh: Configuration complete; ready for start up
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: using the "epoll" event method
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: nginx/1.26.1
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014)
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: OS: Linux 6.6.32-linuxkit
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker processes
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 22
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 23
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 24
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 25
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 26
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 27
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 28
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 29
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 30
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 31
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 32
bpmn_frontend-1       | 2024/07/18 14:32:10 [notice] 1#1: start worker process 33
bpmn_assistant-1      | INFO:     Started server process [1]
bpmn_assistant-1      | INFO:     Waiting for application startup.
bpmn_assistant-1      | INFO:     Application startup complete.
bpmn_assistant-1      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
bpmn_frontend-1       | 192.168.65.1 - - [18/Jul/2024:14:32:14 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
bpmn_frontend-1       | 192.168.65.1 - - [18/Jul/2024:14:32:14 +0000] "GET /assets/index-BqfP9bEH.css HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
bpmn_frontend-1       | 192.168.65.1 - - [18/Jul/2024:14:32:14 +0000] "GET /assets/index-BjMKp_3P.js HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
bpmn_assistant-1      | INFO:     192.168.65.1:61366 - "GET /available_providers HTTP/1.1" 200 OK
bpmn_frontend-1       | 192.168.65.1 - - [18/Jul/2024:14:32:14 +0000] "GET /favicon.ico HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
bpmn_frontend-1       | 192.168.65.1 - - [18/Jul/2024:14:32:14 +0000] "GET /assets/materialdesignicons-webfont-Dp5v-WZN.woff2?v=7.4.47 HTTP/1.1" 304 0 "http://localhost:8080/assets/index-BqfP9bEH.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:35.530 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:36.597 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | INFO:     192.168.65.1:64349 - "POST /determine_intent HTTP/1.1" 200 OK
bpmn_assistant-1      | INFO:     192.168.65.1:64349 - "OPTIONS /talk HTTP/1.1" 200 OK
bpmn_assistant-1      | INFO:     192.168.65.1:64349 - "POST /talk HTTP/1.1" 200 OK
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:36.622 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:37.075 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:55.084 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:55.964 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | INFO:     192.168.65.1:45786 - "POST /determine_intent HTTP/1.1" 200 OK
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:56.008 app.py:81 - Creating a new BPMN process...
bpmn_assistant-1      | [INFO]: 2024-07-18 14:32:56.008 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:04.391 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | [WARNING]: 2024-07-18 14:33:04.393 bpmn_modeling_service.py:51 - Validation error (attempt 1): 'next'
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:04.393 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:18.158 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | [WARNING]: 2024-07-18 14:33:18.161 bpmn_modeling_service.py:51 - Validation error (attempt 2): 'next'
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:18.161 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:34.428 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | [WARNING]: 2024-07-18 14:33:34.430 bpmn_modeling_service.py:51 - Validation error (attempt 3): 'next'
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:34.430 llm_facade.py:55 - Calling LLM
bpmn_assistant-1      | [INFO]: 2024-07-18 14:33:49.905 _client.py:1026 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
bpmn_assistant-1      | [ERROR]: 2024-07-18 14:33:49.907 app.py:91 - Error: Max number of retries reached. Could not create the BPMN process.
bpmn_assistant-1      | Traceback (most recent call last):
bpmn_assistant-1      |   File "/app/src/bpmn_assistant/app.py", line 82, in _modify
bpmn_assistant-1      |     process = bpmn_modeling_service.create_bpmn(
bpmn_assistant-1      |   File "/app/src/bpmn_assistant/services/bpmn_modeling_service.py", line 59, in create_bpmn
bpmn_assistant-1      |     raise Exception(
bpmn_assistant-1      | Exception: Max number of retries reached. Could not create the BPMN process.
bpmn_assistant-1      | INFO:     192.168.65.1:45786 - "POST /modify HTTP/1.1" 500 Internal Server Error

**Comment by jtlicardo** [comment]
Thanks for the bug report, I believe this should be fixed with the following commit: 03c65f27d9820e21b4beb8a32a03f485e13cabf3

Let me know if you encounter any other issues. Thanks!
