### ISSUE TITLE
working with lanes?

### ISSUE THREAD

**Issue by alibama** [jtlicardo/bpmn-assistant#7]
how would you implement lanes in these diagrams?  i'm pleased with the results so far, starting to think about working models 
<img width="1231" alt="Screenshot 2024-07-23 at 12 41 13 AM" src="https://github.com/user-attachments/assets/aaaad75e-c884-48dd-b55a-02e42f726123">

https://www.charlottesville.gov/216/Starting-a-Small-Business is where i'm pulling queries from and the bpmn assistant is helping parse and respond in app.  i want to be able to have the city manager be one lane, the business owner be the other etc...

**Comment by jtlicardo** [comment]
I am using [BPMN auto layout](https://github.com/bpmn-io/bpmn-auto-layout) for diagram layout, which unfortunately does not support models with pools or lanes.

To work around this limitation, you can download the generated BPMN file and use a tool like [bpmn.io](https://demo.bpmn.io/) to manually add the lanes.
