### ISSUE TITLE
character limits, remote serving, jupyter ideas?

### ISSUE THREAD

**Issue by alibama** [jtlicardo/bpmn-assistant#8]
could you explain the character limit?  i'd like to extend that beyond 1000 chars

i'm testing this on a remote server now - http://cville.digital:8080/ but it can't seem to see the API keys, even though it's configured the same as it would be locally - wonder if one of the containers is only seeing localhost?  i'm looking in to it, just thought i would ask

also - got a request to leverage this product in jupyter/colab and wondering your thoughts there.  I was thinking about maybe stripping out the bpmn editor and just having the libraries render bpmn files, and then editing those in camunda or ????  i like the packaged aspect of the product, but for getting people involved in might be simpler to introduce as a workbook - what are your thoughts?

**Comment by jtlicardo** [comment]
Increased the character limit to 10.000 chars, looking good so far with the link you sent me (https://www.charlottesville.gov/216/Starting-a-Small-Business) - expect to see better results with GPT-4o and Claude 3.5 Sonnet.

![image](https://github.com/user-attachments/assets/2c1e09e7-108f-4c36-a2c5-18c298bae552)

I haven't tried to deploy this on a remote server yet, so I'm not entirely sure what's causing the issue. It might be related to the Docker containers, but it's hard to say without more details.

Regarding the idea of leveraging this product in Jupyter, I believe it's important to maintain this as a web app to preserve the intended user experience and functionality. I'm not sure how well the chat interface would translate to a Jupyter environment.
